Madkom\Registries\Domain\Car\Car:
  type: entity

  manyToOne:
    registryId:
      targetEntity: Madkom\Registries\Domain\Car\CarRegistry
      inversedBy: positions
      joinColumn:
        name: registry_id
        referencedColumnName: registry_id

  manyToMany:
    terms:
      targetEntity: Madkom\Registries\Domain\Term
      cascade: ['persist']
      inversedBy: cars
      joinTable:
        name: CarTerms
        joinColumns:
          car_car_id:
            referencedColumnName: car_id
        inverseJoinColumns:
          term_term_id:
            referencedColumnName: term_id

  id:
    id:
      column: car_id
      type: integer
      generator:
        strategy: AUTO

  fields:
    brand:
      type: string(50)
    model:
      type: string(50)
    registrationNumber:
      type: string(10)
    others:
      type: string(255)