Madkom\Registries\Domain\Department\Department:
  type: entity

  manyToMany:
    terms:
      targetEntity: Madkom\Registries\Domain\Term
      mappedBy: whoToNotify

  id:
    department_id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string(50)
    email:
      type: string(50)