Madkom\Registries\Domain\Term:
  type: entity

  id:
    id:
      type: integer
      column: term_id
      generator:
        strategy: AUTO

  fields:
    expiryDate:
      type: datetime
    notifyBefore:
      type: datetime
    whoToNotify:
      type: text