Madkom\Registries\Domain\Term:
  type: entity

  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: term_type
    type: string

  manyToMany:
    cars:
      targetEntity: Madkom\Registries\Domain\Car\Car
      mappedBy: terms

  manyToOne:
    whoToNotify:
      targetEntity: Madkom\Registries\Domain\Department\Department
      inversedBy: terms

  id:
    id:
      type: integer
      column: term_id
      generator:
        strategy: AUTO

  fields:
    expiryDate:
      type: datetime
    notifyBefore:
      type: datetime